Updated method openURL
okta/okta-oidc-ios pull request #300
Opened 2021-07-16 15:49 UTC by oleggnidets-okta

### Problem Analysis (Technical)
The okta-oidc library uses the openURL: API, which has been deprecated since iOS 10.0. The library should be updated to utilize the new API.

### Solution (Technical)
`open(_:options:completionHandler:)` called now.

2021-07-18 13:05 UTC, mikenachbaur-okta requested changes

2021-07-18 13:05 UTC, mikenachbaur-okta commented on Sources/AppAuth/iOS/OKTExternalUserAgentIOSCustomBrowser.m
> +  [[UIApplication sharedApplication] openURL:_appStoreURL options:@{} completionHandler:^(BOOL success) {
Don't you mean requestUrl?

2021-07-19 07:44 UTC, oleggnidets-okta commented on Sources/AppAuth/iOS/OKTExternalUserAgentIOSCustomBrowser.m
> +  [[UIApplication sharedApplication] openURL:_appStoreURL options:@{} completionHandler:^(BOOL success) {
Really, my bad!
Thanks

2021-07-19 16:24 UTC, mikenachbaur-okta approved these changes

2021-07-22 08:16 UTC, merged